export const GET_JOKES_REQUEST = 'GET_JOKES_REQUEST';
export const GET_JOKES_SUCCESS = 'GET_JOKES_SUCCESS';
export const GET_JOKES_FAILURE = 'GET_JOKES_FAILURE';

export const CHANGE_JOKE_COUNT = 'CHANGE_JOKE_COUNT';
export const CHANGE_FIRST_NAME = 'CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = 'CHANGE_LAST_NAME';
export const CHANGE_JOKE_TYPES = 'CHANGE_JOKE_TYPES';

export const GET_JOKE_TYPES_REQUEST = 'GET_JOKE_TYPES_REQUEST';
export const GET_JOKE_TYPES_SUCCESS = 'GET_JOKE_TYPES_SUCCESS';
export const GET_JOKE_TYPES_FAILURE = 'GET_JOKE_TYPES_FAILURE';
